#ifndef OSCILLOSCOPE_GLOBAL_H
#define OSCILLOSCOPE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OSCILLOSCOPE_LIBRARY)
#  define OSCILLOSCOPESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSCILLOSCOPESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OSCILLOSCOPE_GLOBAL_H
