#ifndef SETANDHEALTH_GLOBAL_H
#define SETANDHEALTH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETANDHEALTH_LIBRARY)
#  define SETANDHEALTHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETANDHEALTHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETANDHEALTH_GLOBAL_H
